Added French translations
GitSparTV/GodSentTools pull request #2
Opened 2022-01-14 20:12 UTC by FlorianLeChat

All files with available translations have been translated into French. By the way, nice work Spar! ⭐

2022-01-14 20:28 UTC, GitSparTV commented
Hi, thanks for contributing, I'm uploading all changes from all addons right now, please wait and sync

2022-01-14 20:31 UTC, GitSparTV commented
Check again, for example Second Chance now have formatted parameter

2022-01-15 08:49 UTC, FlorianLeChat commented
The changes have been completed, however it would be cool if the GPU saver addon could also replace the key to open the spawn menu: https://github.com/GitSparTV/GodSentTools/blob/9180de7aa1d98e6b59cf8d2b18949620e48df445/godsenttools_gpu_saver/resource/localization/en/godsenttools_gpu_saver.properties#L9
Because especially in France (and in a smaller degree in the rest of Europe), we use an AZERTY layout and the `Q` key is mostly used to move left, so most people put the bind on the `G` key or to another key. So if this key could also be replaced like you did with Second Chance, it would be really better.

2022-01-15 08:53 UTC, GitSparTV commented
I see, I will change it to lookup binding key

2022-01-15 09:44 UTC, FlorianLeChat commented
Everything is good on my side, I have integrated the latest changes.

2022-01-15 10:47 UTC, GitSparTV requested changes

2022-01-15 10:47 UTC, GitSparTV commented on godsenttools_gpu_saver/resource/localization/fr/godsenttools_gpu_saver.properties
> +godsenttools.gpusaver.osxwarning=Attention ! MacOS détecté, cet addon ne fonctionne pas avec ce système d'exploitation. L'addon sera automatiquement désactivé. Vous pouvez toujours utiliser cet addon
Do you really put spaces before `!` and `:` in your language?
Same question about spaces between « »

2022-01-15 10:58 UTC, FlorianLeChat commented on godsenttools_gpu_saver/resource/localization/fr/godsenttools_gpu_saver.properties
> +godsenttools.gpusaver.osxwarning=Attention ! MacOS détecté, cet addon ne fonctionne pas avec ce système d'exploitation. L'addon sera automatiquement désactivé. Vous pouvez toujours utiliser cet addon
Yes, this is a specification of the French language: https://en.wikipedia.org/wiki/History_of_sentence_spacing#French_and_English_spacing

2022-01-15 11:34 UTC, GitSparTV commented
Alright, I've updated files again little bit.

2022-01-15 12:27 UTC, GitSparTV approved these changes

2022-01-15 20:38 UTC, FlorianLeChat commented
I will wait a few days before updating my pull request again, so that you can make any necessary changes during this time. If you think you're not going to touch the translations anymore, let me know!

2022-01-15 20:39 UTC, GitSparTV commented
I'm done :)

2022-01-16 11:45 UTC, FlorianLeChat commented
Here we go. I also fixed two small inconsistencies in the English translations of the "Pitch Black" addon. Let me know if everything is good for you!

2022-01-16 12:19 UTC, GitSparTV approved these changes

2022-01-16 12:21 UTC, merged

2022-01-16 13:03 UTC, GitSparTV commented
Translations are uploaded to Workshop, everything works for me. Thanks for contribution